INSERT INTO "light_cone"
(id, "name", "path", rarity)
VALUES
('adversarial', 'Adversarial', 'hunt', 3),
('amber', 'Amber', 'preservation', 3),
('arrows', 'Arrows', 'hunt', 3),
('chorus', 'Chorus', 'harmony', 3),
('collapsing-sky', 'Collapsing Sky', 'destruction', 3),
('cornucopia', 'Cornucopia', 'abundance', 3),
('darting-arrow', 'Darting Arrow', 'hunt', 3),
('data-bank', 'Data Bank', 'erudition', 3),
('defense', 'Defense', 'preservation', 3),
('fine-fruit', 'Fine Fruit', 'abundance', 3),
('hidden-shadow', 'Hidden Shadow', 'nihility', 3),
('loop', 'Loop', 'nihility', 3),
('meditation', 'Mediation', 'harmony', 3),
('meshing-cogs', 'Meshing Cogs', 'harmony', 3),
('multiplication', 'Multiplication', 'abundance', 3),
('mutual-demise', 'Mutual Demise', 'destruction', 3),
('passkey', 'Passkey', 'erudition', 3),
('pioneering', 'Pioneering', 'preservation', 3),
('sagacity', 'Sagacity', 'erudition', 3),
('shattered-home', 'Shattered Home', 'erudition', 3),
('void', 'Void', 'nihility', 3),
-- 4*
('a-secret-vow', 'A Secret Vow', 'destruction', 4),
('before-the-tutorial-mission-starts', 'Before the Tutorial Mission Starts', 'nihility', 4),
('carve-the-moon-weave-the-clouds', 'Carve the Moon, Weave the Clouds', 'harmony', 4),
('dance-dance-dance', 'Dance! Dance! Dance!', 'harmony', 4),
('day-one-of-my-new-life', 'Day One of My New Life', 'preservation', 4),
('eyes-of-the-prey', 'Eyes of the Prey', 'nihility', 4),
('fermata', 'Fermata', 'nihility', 4),
('genuises-repose', 'Geniuses'' Repose', 'erudition', 4),
('good-night-and-sleep-well', 'Good Night and Sleep Well', 'nihility', 4),
('landaus-choice', 'Landau''s Choice', 'preservation', 4),
('make-the-world-clamor', 'Make the World Clamor', 'erudition', 4),
('memories-of-the-past', 'Memories of the Past', 'harmony', 4),
('nowhere to run', 'Nowhere to Run', 'destruction', 4),
('only-silence-remains', 'Only Silence Remains', 'hunt', 4),
('past-and-future', 'Past and Future', 'harmony', 4),
('perfect-timing', 'Perfect Timing', 'abundance', 4),
('planetary-rendezvous', 'Planetary Rendezvous', 'harmony', 4),
('post-op-conversation', 'Post-Op Conversation', 'abundance', 4),
('quid-pro-quo', 'Quid Pro Quo', 'abundance', 4),
('resolution-shines-as-pearls-of-sweat', 'Resolution Shines As Pearls of Sweat', 'nihility', 4),
('return-to-darkness', 'Return to Darkness', 'hunt', 4),
('river-flows-in-spring', 'River Flows in Spring', 'hunt', 4),
('shared-feeling', 'Shared Feeling', 'abundance', 4),
('subscribe-to-more', 'Subscribe to More!', 'hunt', 4),
('swordplay', 'Swordplay', 'hunt', 4),
('the-birth-of-the-self', 'The Birth of the Self', 'erudition', 4),
('the-moles-welcome-you', 'The Moles Welcome You', 'destruction', 4),
('the-seriousness-of-breakfast', 'The Seriousness of Breakfast', 'erudition', 4),
('this-is-me', 'This Is Me!', 'preservation', 4),
('today-is-another-peaceful-day', 'Today is Another Peaceful Day', 'erudition', 4),
('trend-of-the-universal-market', 'Trend of the Universal Market', 'preservation', 4),
('under-the-blue-sky', 'Under the Blue Sky', 'destruction', 4),
('warmth-shortens-cold-nights','Warmth Shortens Cold Nights', 'abundance', 4),
('we-are-wildfire','We Are Wildfire', 'preservation', 4),
('we-will-meet-again','We Will Meet Again', 'nihility', 4),
('woof-walk-time', 'Woof! Walk Time!', 'destruction', 4),
-- 5*
('before-dawn', 'Before Dawn', 'erudition', 5),
('cruising-in-the-stellar-sea', 'Cruising in the Stellar Sea', 'hunt', 5),
('echoes-of-the-coffin', 'Echoes of the Coffin', 'abundance', 5),
('in-the-name-of-the-world', 'In the Name of the World', 'nihility', 5),
('in-the-night', 'In the Night', 'hunt', 5),
('incessant-rain', 'Incessant Rain', 'nihility', 5),
('moment-of-victory', 'Moment of Victory', 'preservation', 5),
('night-on-the-milky-way', 'Night on the Milky Way', 'erudition', 5),
('on-the-fall-of-an-aeon', 'On the Fall of an Aeon', 'destruction', 5),
('sleep-like-the-dead', 'Sleep Like the Dead', 'hunt', 5),
('something-irreplaceable', 'Something Irreplaceable', 'destruction', 5),
('texture-of-memories', 'Texture of Memories', 'preservation', 5),
('the-battle-isnt-over', 'The Battle Isn''t Over', 'harmony', 5),
('the-unreachable-side', 'The Unreachable Side', 'destruction', 5),
('time-waits-for-no-one', 'Time Waits for No One', 'abundance', 5);