# fly.toml app configuration file generated for dev-db-api on 2023-08-05T00:59:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dev-db-api"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"
