name: ⚡ Deployment

on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: ⚡ Deploy
        run: flyctl deploy --remote-only --app ${{ inputs.domain }}-db-api --build-target db-api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
