name: ⚡ Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deployment
        run: flyctl deploy --config ./.flyio/frontend.fly.toml --app stellaron-${{ inputs.environment }}-frontend --remote-only

  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deployment
        run: flyctl deploy --config ./.flyio/api.fly.toml --app stellaron-${{ inputs.environment }}-api --remote-only
