name: ⚡ Deployment

on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: ⚡ db-api
        run: flyctl deploy --config ./.flyio/db-api.fly.toml --app ${{ inputs.domain }}-db-api --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
